### ISSUE TITLE
Color pallets for the Header Color Section not fully appearing 

### ISSUE THREAD

**Issue by Florin415** [ColorlibHQ/dizzi#2]
If we try to change the colors in the Header Color Section for the last 3 elements( Dropdown menu colors ) , the collor pallet will not fully load : 
Example : 
https://prnt.sc/upxsbe
https://prnt.sc/upxt7x
https://prnt.sc/upxtw1

**Comment by codepixar** [comment]
Thanks @Florin415 for your query. As we are using the 'Epsilon Framework' & 'Epsilon Dashboard' library with each of our wp themes, the customizer color options and theme options are coming from there. We are just using their library with our theme. So, the bug is coming from there. So, they should update the issue by their end.

Thanks
